FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Majestic Thai

Majestic Thai is a simple API allowing consumers to view menu items and submit an order.

## Menu Collection [/dishes]

### List All Menu Items [GET]

+ Response 200 (application/json)

        [
            {
                "title": "Pad Thai"
            }
        ]
        
## Menu Item [/dishes/{dish_id}]
+ Parameters
    + dish_id (number) - ID of the Dish in the form of an integer

### List Details [GET]

+ Response 200 (application/json)

        [
            {
                "_id": "98347958",
                "name": "Pad Thai",
                "description": "Yummy thai food",
                "price": "$12.00"
            }
        ]
        
## Order Collection [/orders]

### List All Orders [GET]

+ Response 200 (application/json)

        [
            {
                "time": "2014-11-11T08:40:51.620Z",
                "user_name": "Padthailover2"
            }
        ]
        
## Order Item [/orders/{order_id}]
+ Parameters
    + order_id (number) - ID of the Order in the form of an integer


### List All Menu Items [GET]

+ Response 200 (application/json)

        [
            {
               "time": "2014-11-11T08:40:51.620Z",
               "_id":"8457028345",
                "user_name": "Padthailover2",
                "total": 3400,
                "items": [
                    {
                        "name": "Pad Thai",
                        "descrition": "Yummy thai food",
                        "price": 900
                    },{
                        "name": "Red Curry",
                        "descrition": "Yummyer thai food",
                        "price": 1900
                    },
                ]
            }
        ]