FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Majestic Thai

Majestic Thai is a simple API allowing consumers to view menu items and submit an order.

## Menu Collection [/dishes]

### List All Menu Items [GET]

+ Response 200 (application/json)

        [
            {
                "title": "Pad Thai"
            },
            {
                "title": "Green Curry"
            }
        ]
        
## Menu Item [/dishes/{dish_id}]
+ Parameters
    + dish_id (number) - ID of the Dish in the form of an integer

### List Details [GET]

+ Response 200 (application/json)

        [
            {
                "url": "/dishes/1",
                "name": "Pad Thai",
                "dish_id": 1,
                "description": "Yummy thai food",
                "price": "$12.00"
            },
            {
                "url": "/dishes/2",
                "name": "Green Curry",
                "dish_id": 2,
                "description": "Yummyiest thai food",
                "price": 1500
            }
        ]
        
## Order Collection [/orders]

### List All Orders [GET]

+ Response 200 (application/json)

        [
            {
                "time": "2014-11-11T08:40:51.620Z",
                "user_name": "Padthailover2"
            },
            {
                "time": "2015-03-11T08:40:51.620Z",
                "user_name": "ironyardgrad7",
            }
        ]
        
## Order Item [/orders/{order_id}]
+ Parameters
    + order_id (number) - ID of the Order in the form of an integer


### List All Menu Items [GET]

+ Response 200 (application/json)

        [
            {
               "time": "2014-11-11T08:40:51.620Z",
               "order_id":1,
                "user_name": "Padthailover2",
                "total": 3400,
                "items": [
                    {
                        "name": "Pad Thai",
                        "descrition": "Yummy thai food",
                        "price": 900
                    },{
                        "name": "Red Curry",
                        "descrition": "Yummyer thai food",
                        "price": 1900
                    },
                ]
            }, 
            {
               "time": "2015-03-11T08:40:51.620Z",
               "order_id":2,
                "user_name": "ironyardgrad7",
                "total": 1400,
                "items": [
                    {
                        "name": "Green Curry",
                        "descrition": "Yummy thai food",
                        "price": 1000
                    },{
                        "name": "Red Curry",
                        "descrition": "Yummyer thai food",
                        "price": 1900
                    },
                ]
            }
        ]